name: Build Qt App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'  # You can change to latest if needed

      - name: Configure with CMake
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build App
        run: |
          cd build
          cmake --build .
